// Code generated by command: go run asm.go -out out/grain_amd64.s -stubs out/stub_amd64.go -pkg grain. DO NOT EDIT.

// +build gc,!purego

package grain

//go:noescape
func next(s *state) uint32

//go:noescape
func accumulate(s *state, ms uint16, pt uint16)
