// Code generated by command: go run asm.go -out out/ascon.s -stubs out/stub.go -pkg ascon. DO NOT EDIT.

// +build amd64,gc,!purego

package ascon

//go:noescape
func p12(s *state)

//go:noescape
func p8(s *state)

//go:noescape
func p6(s *state)

//go:noescape
func round(s *state, C uint64)
